export const uploadableResourceFileTypes = {
  resource: 'RESOURCE_FILE',
  resourceProfileImage: 'RESOURCE_PROFILE_IMAGE',
  resourceType: 'RESOURCE_TYPE',
  resourceCategory: 'RESOURCE_CATEGORY',
  resourceSubCategory: 'RESOURCE_SUB_CATEGORY',
  crs: 'CONSTRUCTION_RELATED_SERVICES',
  studyLevel: 'RESOURCE_STUDY_LEVEL',
  workExperience: 'RESOURCE_WORK_EXPERIENCE',
  salary: 'RESOURCE_SALARY',
  resourceStudyField: 'RESOURCE_STUDY_FIELD',
  resourceStudyLevel: 'RESOURCE_STUDY_LEVEL',
  resourceSalary: 'RESOURCE_SALARY',
  resourceWorkExperience: 'RESOURCE_WORK_EXPERIENCE',
  resourceQuantityPrice: 'RESOURCE_QUANTITY_PRICE'
} as const;
export const uploadablePhotoTypes = {
  stakeholder_profile_photo: 'STAKEHOLDER_PROFILE_PHOTO',

  project_profile_photo: 'PROJECT_PROFILE_PHOTO',
  user_profile_photo: 'USER_PROFILE_PHOTO',
  resource: 'RESOURCE',
  resourceBrand: 'RESOURCE_BRAND',
  resourceSpecification: 'RESOURCE_SPECIFICATION',
  resourceType: 'RESOURCE_TYPE',
  user_cover_photo: 'USER_COVER_PHOTO'
} as const;

export const uploadableProjectFileTypes = {
  project: 'PROJECT',
  time: 'TIME',
  plan: 'PROJECT_PLAN',
  report: 'PROJECT_REPORT',
  building_envelope_material: 'BUILDING_ENVELOPE_MATERIAL',
  building_dimension_detail: 'BUILDING_DIMENSION_DETAIL',
  solar_energy: 'SOLAR_ENERGY',
  wind_energy: 'WIND_ENERGY',
  transformer_type: 'TRANSFORMER_TYPE',
  extension_time: 'EXTENSION_TIME',
  variation: 'VARIATION_TYPE',
  payment: 'PAYMENT_TYPE',
  bond: 'BOND',
  stakeholder: 'STAKEHOLDER',
  projectType: 'PROJECT_TYPE',
  projectCategory: 'PROJECT_CATEGORY',
  projectSubCategory: 'PROJECT_SUB_CATEGORY',
  masterStatus: 'MASTER_STATUS',
  file: 'File',
  resource: 'RESOURCE',
  certificate: 'CERTIFICATE',
  stakeholderPhone: 'STAKEHOLDER_PHONE',
  stakeholderEmail: 'STAKEHOLDER_EMAIL',
  stakeholderOperationLocation: 'STAKEHOLDER_OPERATION_LOCATION',
  stakeholderContactPerson: 'STAKEHOLDER_CONTACT_PERSON',
  training: 'TRAINING',
  regulation: 'REGULATION',
  other: {
    buildingDimensionDetail: 'BUILDING_DIMENSION_DETAIL',
    port: 'PORT',
    telecomInfrastructure: 'TELECOM_INFRASTRUCTURE',
    buildingEnvelopMaterial: 'BUILDING_ENVELOP_MATERIAL',
    roadInfo: 'ROAD_INFO',
    roadSegment: 'ROAD_SEGMENT',
    roadLayer: 'ROAD_LAYER',
    generatingCapacity: 'GENERATING_CAPACITY',
    turbineInfo: 'TURBINE_INFO',
    hydroElectricDam: 'HYDRO_ELECTRIC_DAM',
    solarEnergy: 'SOLAR_ENERGY',
    windEnergy: 'WIND_ENERGY',
    transformerType: 'TRANSFORMER_TYPE',
    transformer: 'TRANSFORMER',
    transmissionLine: 'TRANSMISSION_LINE',
    electricTower: 'ELECTRIC_TOWER',
    railway: 'RAILWAYS',
    railwayStation: 'RAILWAYSTATION',
    reservoirInfo: 'RESERVOIR_INFO',
    spillwayInfo: 'SPILLWAY_INFO',
    irrigationCapacity: 'IRRIGATION_CAPACITY',
    waterIrrigationDam: 'WATER_IRRIGATION_DAM'
  }
} as const;
export const uploadableStakeholderFileTypes = {
  stakeholder: 'STAKEHOLDER',
  stakeholderInfo: 'STAKEHOLDER_INFO',
  stakeholderCertificate: 'STAKEHOLDER_CERTIFICATE',
  stakeholderTotalEmp: 'STAKEHOLDER_TOTAL_EMP',
  stakeholderTraining: 'STAKEHOLDER_TRAINING',
  stakeholderRegulation: 'STAKEHOLDER_REGULATION',
  stakeholderFieldOfStudy: 'STAKEHOLDER_FIELD_OF_STUDY',
  stakeholderSudyPreiod: 'STAKEHOLDER_STUDY_PERIOD',
  stakeholderGraduates: 'STAKEHOLDER_GRADUATES',
  stakeholderServices: 'STAKEHOLDER_SERVICES',
  stakeholderType: 'STAKEHOLDER_TYPE',
  stakeholderCategory: 'STAKEHOLDER_CATEGORY',
  stakeholderSubCategory: 'STAKEHOLDER_SUB_CATEGORY',
  ownershipType: 'OWNERSHIP_TYPE',
  businessField: 'BUSINESS_FIELD',
  studyLevel: 'STUDY_LEVEL',
  studyProgram: 'STUDY_PROGRAM',
  studyField: 'STUDY_FIELD',
  education: 'EDUCATION',
  employeeAge: 'EMPLOYEE_AGE',
  workExperience: 'WORK_EXPERIENCE',
  ageLevel: 'AGE_LEVEL',
  other: {
    stakeholderStudyField: 'STAKEHOLDER_STUDY_FIELD',
    studyPeriodCost: 'STUDY_PERIOD_COST',
    constructionRelatedService: 'CONSTRUCTION_RELATED_SERVICE',
    stakeholderService: 'STAKEHOLDER_SERVICE'
  }
} as const;
